# .streamlit/secrets.toml  (LOCAL only â€” don't commit)
[postgres]
host = "seu_host_do_banco_aqui"    # ex: db.exemplo.com ou localhost
port = 5432
database = "PNL"
user = "ZenNohDev"
password = "SUA_SENHA_AQUI"
